### ISSUE TITLE
Cannot read property 'delete' of undefined

### ISSUE THREAD

**Issue by FantasyIsBae** [ThreeLetters/HashBounds#9]
I have come across this issue when using OpenAgar.
I don't know if this is a problem with my machine or the actual npm package .
Anyways i wasn't sure where to post this issue so i just posted here 😄 

Full error that i received : 
 
```
Cannot read property 'delete' of undefined
TypeError: Cannot read property 'delete' of undefined
    at Grid.delete (C:\Users\Fantasy\Desktop\OpenAgar-master\node_modules\hashbounds\Grid.js:130:30)
    at HashBounds.delete (C:\Users\Fantasy\Desktop\OpenAgar-master\node_modules\hashbounds\index.js:85:44)
    at HashBounds.update (C:\Users\Fantasy\Desktop\OpenAgar-master\node_modules\hashbounds\index.js:58:20)
    at WorldModel.update (C:\Users\Fantasy\Desktop\OpenAgar-master\source\core\worldModel.js:87:20)
    at Main.updateHash (C:\Users\Fantasy\Desktop\OpenAgar-master\source\core\main.js:1229:25)
    at upt.forEach (C:\Users\Fantasy\Desktop\OpenAgar-master\source\core\main.js:1210:18)
    at Array.forEach (native)
    at Main.updatePlayerNodes (C:\Users\Fantasy\Desktop\OpenAgar-master\source\core\main.js:1208:13)
    at Main.mloop (C:\Users\Fantasy\Desktop\OpenAgar-master\source\core\main.js:1078:18)
    at Main.<anonymous> (C:\Users\Fantasy\Desktop\OpenAgar-master\source\core\main.js:1062:18)
```

**Comment by Andrews54757** [comment]
This is a problem with OpenAgar. This is fixed in https://github.com/AJS-development/OpenAgar/pull/68
